apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-rebalancer
  namespace: default
spec:
  schedule: "1 1,9,17 * * *"
  timeZone: "Asia/Seoul"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-rebalancer
          restartPolicy: Never
          containers:
            - name: pod-rebalancer
              image: harbor.local/library/pod-rebalancer:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: pod-rebalancer-config
                - secretRef:
                    name: pod-rebalancer-secret
                    optional: true

